### ISSUE TITLE
StackOverflowError when calling Archetype#hashCode

### ISSUE THREAD

**Issue by JohannesOehm** [openEHR/java-libs#31]
Hello, when I'm calling `Archetype.toString()`, I get the following error:

    Exception in thread "main" java.lang.StackOverflowError
        at org.openehr.rm.common.resource.ResourceDescriptionItem.hashCode(ResourceDescriptionItem.java:210)
        at java.util.Objects.hashCode(Objects.java:98)
        at java.util.HashMap$Node.hashCode(HashMap.java:296)
        at java.util.AbstractMap.hashCode(AbstractMap.java:507)
        at org.openehr.rm.common.resource.ResourceDescription.hashCode(ResourceDescription.java:215)
        at org.apache.commons.lang.builder.HashCodeBuilder.append(HashCodeBuilder.java:909)
        at org.openehr.rm.common.resource.AuthoredResource.hashCode(AuthoredResource.java:186)
        at org.openehr.rm.common.resource.ResourceDescription.hashCode(ResourceDescription.java:227)
        at org.apache.commons.lang.builder.HashCodeBuilder.append(HashCodeBuilder.java:909)
        at org.openehr.rm.common.resource.AuthoredResource.hashCode(AuthoredResource.java:186)
        at org.openehr.rm.common.resource.ResourceDescription.hashCode(ResourceDescription.java:227)
        at org.apache.commons.lang.builder.HashCodeBuilder.append(HashCodeBuilder.java:909)
        at org.openehr.rm.common.resource.AuthoredResource.hashCode(AuthoredResource.java:186)
        at org.openehr.rm.common.resource.ResourceDescription.hashCode(ResourceDescription.java:227)
        at org.apache.commons.lang.builder.HashCodeBuilder.append(HashCodeBuilder.java:909)
        at org.openehr.rm.common.resource.AuthoredResource.hashCode(AuthoredResource.java:186)
        at org.openehr.rm.common.resource.ResourceDescription.hashCode(ResourceDescription.java:227)
        at org.apache.commons.lang.builder.HashCodeBuilder.append(HashCodeBuilder.java:909)
        at org.openehr.rm.common.resource.AuthoredResource.hashCode(AuthoredResource.java:186)
        at org.openehr.rm.common.resource.ResourceDescription.hashCode(ResourceDescription.java:227)
        at org.apache.commons.lang.builder.HashCodeBuilder.append(HashCodeBuilder.java:909)
        at org.openehr.rm.common.resource.AuthoredResource.hashCode(AuthoredResource.java:186)
        at org.openehr.rm.common.resource.ResourceDescription.hashCode(ResourceDescription.java:227)
        at org.apache.commons.lang.builder.HashCodeBuilder.append(HashCodeBuilder.java:909)
        at org.openehr.rm.common.resource.AuthoredResource.hashCode(AuthoredResource.java:186)
        [....]

The bug seems to result from `ResourceDescription` using its `parentResource` field (which is the archetype) as part of its hashCode. I don't know if this is intentional.

This bug is annoying because it also breaks `Archetype#toString`.

**Comment by icorbal** [comment]
I think the call to `parentResource` inside `ResourceDescription.hashCode()` is not necessary and would always give a StackOverflow (please, anyone, correct me if I'm wrong). I've removed it from the method, it should be fine to call `toString()` now.

**Comment by JohannesOehm** [comment]
At least for my case, the rest still works. Thank You!
